/*
 * Vendor the HugeIcons set the Studio draws with.
 *
 *   node lib/make-icons.mjs [--check]
 *
 * The Studio had no icons at all. Optics has an icon layer, but it is built on
 * Material Symbols — the `.icon--*` modifiers set variable-font axes only that
 * family has — and this is not that set. What Optics does provide is
 * `.custom-icons`, which sizes an inline svg to its box, and nothing that stops a
 * font-based set living beside it. So HugeIcons goes in as itself.
 *
 * Fetched here rather than linked from the page, for the reason every other asset
 * in this toolkit is vendored: the Studio is hosted by a desktop app that has to
 * start with no network, and an icon set that arrives over HTTP is a UI that
 * renders as empty boxes on a plane. It also keeps the set id out of the running
 * app — the id is a licence-bound URL, and the page never needs it.
 *
 * The whole set is taken, not a subset of what the UI happens to use today. The
 * saving would be ~340KB of CSS on a local file, and the cost would be that adding
 * an icon means remembering to regenerate. Wrong trade for a desktop app.
 */
import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");
const OUT = join(ROOT, "brand", "icons");

/**
 * The set, as published for this licence.
 *
 * RoleModel's HugeIcons set id. It selects which styles and icons the CSS carries,
 * so it is configuration rather than a secret — but it is also the only thing
 * standing between a stranger and our licensed download, so it lives here and not
 * in anything the Studio serves.
 */
const SET_ID = process.env.HUGEICONS_SET ?? "blhjf1ha8k";
const SET_CSS = `https://sets.hugeicons.com/${SET_ID}.css`;

/** Modern, because the older UA gets served per-weight TTFs instead of woff2. */
const UA =
	"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

const argv = process.argv.slice(2);
const check = argv.includes("--check");

const get = async (url, kind) => {
	const res = await fetch(url, { headers: { "user-agent": UA } });
	if (!res.ok) throw new Error(`${kind}: ${url} answered ${res.status}`);
	return kind === "css" ? res.text() : Buffer.from(await res.arrayBuffer());
};

/**
 * Point the @font-face at the file we serve, and drop the formats nothing reads.
 *
 * The published CSS lists eot, woff, ttf and svg alongside woff2 — a 2014 fallback
 * chain. Every one of those is a URL back to hugeicons.com, so leaving them in
 * would mean the page still reaches for the network when woff2 is right there. One
 * local source, and the rest go.
 *
 * The URL carries the set's own id, and it has to.
 *
 * A codepoint here means nothing on its own — it means whatever the font paired
 * with this stylesheet says it means. Upstream reissues the set and every one of
 * them can move: 5502 icons became 6081 in one regeneration. The filename does
 * not change, so a browser holding the previous font applied the new
 * stylesheet's codepoints to it and drew the wrong glyph for every icon in the
 * app. Nothing errors — each icon is a real glyph, just not the one asked for —
 * which makes it read as the UI having been vandalised rather than as a stale
 * cache. Tie the two together so the pair can only ever be fetched as a pair.
 */
function localise(css, families, stamp) {
	return css.replace(/@font-face\s*\{[\s\S]*?\}/g, (block) => {
		const family = /font-family:\s*"([^"]+)"/.exec(block)?.[1];
		if (!family) return block;
		families.add(family);
		return [
			"@font-face {",
			`  font-family: "${family}";`,
			`  src: url("/icons/${family}.woff2?v=${stamp}") format("woff2");`,
			"  font-weight: normal;",
			"  font-style: normal;",
			"  font-display: block;",
			"}",
		].join("\n");
	});
}

const HEADER = (families, count) => `/* GENERATED by lib/make-icons.mjs in the rolemodel-openscreen toolkit.
 * DO NOT EDIT. Run \`pnpm run icons\`; \`pnpm run check\` fails on drift.
 *
 * HugeIcons, vendored. ${count} icons across ${families.length} famil${families.length === 1 ? "y" : "ies"}:
 * ${families.join(", ")}.
 *
 * Served from this repo rather than linked, because the Studio is hosted by a
 * desktop app that has to start with no network. The published stylesheet's eot,
 * woff, ttf and svg fallbacks are stripped: each was a URL back to hugeicons.com,
 * so keeping them would mean reaching for the network with woff2 already local.
 */
`;

const short = (s) => createHash("sha256").update(s).digest("hex").slice(0, 12);

const build = async () => {
	const raw = await get(SET_CSS, "css");
	const families = new Set();
	/* Stamped from the upstream stylesheet, not from SET_ID: upstream reissued
	   the same set id with 6081 icons where it had 5502, so the id is not
	   evidence that the codepoints are unchanged. This hash is. */
	const css = localise(raw, families, short(raw));
	const names = new Set([...css.matchAll(/\.hgi-([a-z0-9-]+)::before/g)].map((m) => m[1]));
	return { css: `${HEADER([...families], names.size)}\n${css.trim()}\n`, families: [...families], count: names.size };
};

const { css, families, count } = await build();
const cssPath = join(OUT, "hugeicons.css");
const have = existsSync(cssPath) ? await readFile(cssPath, "utf8") : null;

if (check) {
	const missing = families.filter((f) => !existsSync(join(OUT, `${f}.woff2`)));
	if (have === css && !missing.length) {
		console.log(`\n  brand/icons/ matches set ${SET_ID} — ${count} icons, ${families.length} font file(s)\n`);
		process.exit(0);
	}
	console.error(`\n  ✗ brand/icons/ is out of date`);
	if (have !== css) console.error(`      css: have ${have === null ? "(missing)" : short(have)}   want ${short(css)}`);
	for (const f of missing) console.error(`      missing ${f}.woff2`);
	console.error("\n  run `pnpm run icons`\n");
	process.exit(1);
}

await mkdir(OUT, { recursive: true });
await writeFile(cssPath, css);
console.log("");
console.log(`  set       ${SET_ID}`);
console.log(`  icons     ${count}`);
for (const family of families) {
	// The published src carries a cache-busting query; the file behind it does not
	// change per style, so the name is enough to fetch it.
	const url = `https://use.hugeicons.com/icon-font/${family}.woff2`;
	const bytes = await get(url, "font");
	await writeFile(join(OUT, `${family}.woff2`), bytes);
	console.log(`  font      brand/icons/${family}.woff2  (${Math.round(bytes.length / 1024)}KB)`);
}
console.log(`  css       brand/icons/hugeicons.css  (${Math.round(css.length / 1024)}KB)`);
console.log("");
