/**
 * Bring Optics in as Optics, not as a copy of it.
 *
 * What this used to do: read a 791KB Figma variables export and flatten it into
 * 1160 static hexes, one `light-dark()` pair per token. That produced something
 * that *looked* like Optics and behaved like a photograph of it. Real Optics
 * does not ship hexes at all — every ramp is computed in CSS from three
 * numbers:
 *
 *   --op-color-primary-plus-eight: light-dark(
 *     hsl(var(--op-color-primary-h) var(--op-color-primary-s) 98%),
 *     hsl(var(--op-color-primary-h) var(--op-color-primary-s) 14%)
 *   );
 *
 * So the flattened version lost the thing that makes the system a system: set
 * `--op-color-primary-h` and all 480-odd tokens re-tint. Flattened, they cannot
 * move, and every Optics release silently widened the gap between our palette
 * and the real one. `light-dark()` and `color-scheme: light dark` were already
 * in the package — the generator was reimplementing them.
 *
 * What this does now:
 *
 *   1. Vendors `@rolemodel/optics` verbatim into brand/optics/optics.css. Byte
 *      for byte, never edited. `--check` compares hashes, so a hand-edit is a
 *      failed build rather than a mystery.
 *   2. Generates brand/optics/rolemodel-scales.css from the Figma export — and
 *      *only* the tokens the published package does not define. Today that is
 *      the sub-brand scales (academy, lcad, docks, decks, railing, building,
 *      airfield, flow), which are RoleModel's and are not in the open-source
 *      release. The filter reads the vendored file, so as Optics publishes more,
 *      this file shrinks on its own instead of shadowing the real tokens.
 *
 * Why vendored rather than resolved from node_modules at runtime: the Homebrew
 * formula does `libexec.install Dir["*"]` and never runs `npm install`, so a
 * brew install has no node_modules. The committed CSS is what ships. The
 * package is a devDependency because it is a build input, not a runtime one.
 *
 * Upgrading Optics is now the normal thing:
 *
 *   npm run optics:latest      # is there a newer one?
 *   npm i -D @rolemodel/optics@latest && npm run optics
 *
 *   node lib/optics-css.mjs [--check]
 */
import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, "..");

// The no_icons build: nothing here uses Material Symbols, and that variant is
// the same tokens without pulling an icon font over the network on every video
// render. The Noto @import it does keep is Optics' own and is left alone —
// our own CSS sets font-family from brand/tokens.json, so nothing depends on it.
const UPSTREAM = "dist/css/optics+no_icons.css";
const PKG = "@rolemodel/optics";

export const VENDORED = "brand/optics/optics.css";
export const SUPPLEMENT = "brand/optics/rolemodel-scales.css";
export const MANIFEST = "brand/optics/manifest.json";

const sha = (s) => createHash("sha256").update(s).digest("hex");

/** Flatten one mode of the Figma export into [cssVarName, hex] pairs. */
function collect(node, prefix, out) {
	for (const [key, value] of Object.entries(node)) {
		if (!value || typeof value !== "object") continue;
		if (value.$value !== undefined) {
			// Prefer the name Optics itself publishes; fall back to the tree path so
			// a token missing $codeSyntax still lands somewhere sensible.
			const web = value.$codeSyntax?.WEB;
			const name = web ? web.replace(/^var\(|\)$/g, "") : `--op-color-${prefix}-${key}`.replace(/-{2,}/g, "-");
			out.set(name, String(value.$value).toLowerCase());
			continue;
		}
		collect(value, prefix ? `${prefix}-${key}` : key, out);
	}
	return out;
}

/** Every custom property the published package defines. */
function definedBy(css) {
	const names = new Set();
	for (const m of css.matchAll(/^\s*(--[a-z0-9-]+)\s*:/gim)) names.add(m[1]);
	return names;
}

/**
 * The families in the export that published Optics does not carry. Derived, not
 * hardcoded: a name is ours if the package never defines it.
 */
function familyOf(name) {
	return name.replace(/^--op-color-/, "").split("-")[0];
}

function buildSupplement(light, dark, published) {
	const rows = [];
	const families = new Map();

	for (const [name, l] of light) {
		if (published.has(name)) continue; // real Optics owns it — never shadow it
		const d = dark.get(name);
		rows.push([name, d && d !== l ? `light-dark(${l}, ${d})` : l]);
		const f = familyOf(name);
		families.set(f, (families.get(f) ?? 0) + 1);
	}
	rows.sort((a, b) => a[0].localeCompare(b[0]));

	const names = [...families.keys()].sort();
	const head = [
		"/*",
		" * GENERATED by lib/optics-css.mjs — do not edit.",
		" *",
		" * RoleModel scales that the open-source Optics release does not publish,",
		" * read out of brand/optics-tokens.json (the Figma export). Everything the",
		" * package does define is deliberately absent from this file: Optics owns",
		" * those, computes them from --op-color-primary-h/s/l, and a static copy",
		" * here would shadow the live ones and stop them re-tinting.",
		" *",
		` * Families: ${names.join(", ") || "(none)"}`,
		" *",
		" * These are flat light/dark pairs rather than computed ramps because the",
		" * export is what we have — Figma resolves them before writing them out.",
		" * If Optics ever publishes these scales, they vanish from here on the next",
		" * `npm run optics` and the real computed versions take over.",
		" */",
		":root {",
	];
	return [...head, ...rows.map(([n, v]) => `  ${n}: ${v};`), "}", ""].join("\n");
}

export async function buildOptics(root = ROOT) {
	const pkgDir = resolve(root, "node_modules", PKG);
	if (!existsSync(pkgDir)) {
		throw new Error(
			`${PKG} is not installed. It is a devDependency and the source for brand/optics/.\n` +
				"  npm install",
		);
	}
	const version = JSON.parse(await readFile(resolve(pkgDir, "package.json"), "utf8")).version;
	const upstream = await readFile(resolve(pkgDir, UPSTREAM), "utf8");
	const published = definedBy(upstream);

	const raw = JSON.parse(await readFile(resolve(root, "brand/optics-tokens.json"), "utf8"));
	const styles = raw["0"]?.["Color Styles"]?.modes;
	if (!styles?.Light || !styles?.Dark) {
		throw new Error("brand/optics-tokens.json has no Color Styles Light/Dark modes");
	}
	const light = collect(styles.Light, "", new Map());
	const dark = collect(styles.Dark, "", new Map());

	const supplement = buildSupplement(light, dark, published);
	const ours = [...supplement.matchAll(/^\s*(--[a-z0-9-]+)\s*:/gm)].length;

	const manifest = {
		$comment: `GENERATED by lib/optics-css.mjs. ${VENDORED} is ${PKG} verbatim — do not edit either by hand.`,
		package: PKG,
		version,
		upstreamFile: UPSTREAM,
		vendoredSha256: sha(upstream),
		supplementSha256: sha(supplement),
		tokens: { published: published.size, rolemodelOnly: ours },
	};

	return {
		version,
		files: {
			[VENDORED]: upstream,
			[SUPPLEMENT]: supplement,
			[MANIFEST]: `${JSON.stringify(manifest, null, "\t")}\n`,
		},
		manifest,
	};
}

/**
 * Verifies what is committed without needing node_modules — release.yml runs
 * node directly and never installs. So this checks the repo against itself: the
 * manifest's hashes must match the two CSS files beside it. Comparing against
 * the *installed* package is an extra assertion, made only when it is there.
 */
export async function checkOptics(root = ROOT) {
	const read = (p) => readFile(resolve(root, p), "utf8");
	const problems = [];

	let manifest;
	try {
		manifest = JSON.parse(await read(MANIFEST));
	} catch {
		return [`${MANIFEST} is missing or unparseable — run \`npm run optics\`.`];
	}

	for (const [file, key] of [
		[VENDORED, "vendoredSha256"],
		[SUPPLEMENT, "supplementSha256"],
	]) {
		const body = await read(file).catch(() => null);
		if (body === null) problems.push(`${file} is missing — run \`npm run optics\`.`);
		else if (sha(body) !== manifest[key]) {
			problems.push(`${file} does not match ${MANIFEST} (${key}) — it was hand-edited, or the export changed.`);
		}
	}

	// The supplement must never define a token the vendored package already
	// owns; that is the whole contract of the split, and it is cheap to assert.
	const vendored = await read(VENDORED).catch(() => "");
	const supplement = await read(SUPPLEMENT).catch(() => "");
	if (vendored && supplement) {
		const published = definedBy(vendored);
		const shadowed = [...definedBy(supplement)].filter((n) => published.has(n));
		if (shadowed.length) {
			problems.push(`${SUPPLEMENT} shadows ${shadowed.length} real Optics tokens: ${shadowed.slice(0, 5).join(", ")}`);
		}
	}

	if (existsSync(resolve(root, "node_modules", PKG))) {
		const built = await buildOptics(root);
		if (built.version !== manifest.version) {
			problems.push(`brand/optics/ is Optics ${manifest.version}, but ${built.version} is installed — run \`npm run optics\`.`);
		}
		for (const [file, body] of Object.entries(built.files)) {
			const on = await read(file).catch(() => null);
			if (on !== null && on !== body) problems.push(`${file} is stale — run \`npm run optics\`.`);
		}
	}
	return problems;
}

/** Ask npm what the newest Optics is. The only network call in here. */
async function latestVersion() {
	const res = await fetch(`https://registry.npmjs.org/${PKG.replace("/", "%2f")}`);
	if (!res.ok) throw new Error(`npm registry said ${res.status}`);
	return (await res.json())["dist-tags"].latest;
}

if (import.meta.url === `file://${process.argv[1]}`) {
	const check = process.argv.includes("--check");

	if (process.argv.includes("--latest")) {
		const m = JSON.parse(await readFile(resolve(ROOT, MANIFEST), "utf8"));
		const latest = await latestVersion();
		if (latest === m.version) {
			console.log(`Optics ${m.version} is the latest.`);
		} else {
			console.log(`Optics ${latest} is out; brand/optics/ is on ${m.version}.`);
			console.log(`  npm i -D ${PKG}@${latest} && npm run optics`);
			process.exitCode = 1;
		}
	} else if (check) {
		const problems = await checkOptics();
		if (problems.length) {
			for (const p of problems) console.error(`  ✗ ${p}`);
			process.exit(1);
		}
		const m = JSON.parse(await readFile(resolve(ROOT, MANIFEST), "utf8"));
		console.log(
			`brand/optics/ is up to date (Optics ${m.version}: ${m.tokens.published} published tokens, ` +
				`${m.tokens.rolemodelOnly} RoleModel-only).`,
		);
	} else {
		const { files, manifest } = await buildOptics();
		await mkdir(resolve(ROOT, "brand/optics"), { recursive: true });
		for (const [file, body] of Object.entries(files)) {
			await writeFile(resolve(ROOT, file), body);
			console.log(`wrote ${file}`);
		}
		console.log(
			`Optics ${manifest.version}: ${manifest.tokens.published} tokens from the package, ` +
				`${manifest.tokens.rolemodelOnly} RoleModel-only from the Figma export.`,
		);
	}
}
