#!/usr/bin/env node
/**
 * Derives `brand/tokens.json` from the Optics token export.
 *
 * Before this, the video palette was hand-transcribed hexes copied out of the
 * Academy DESIGN.md — a second source of truth that could quietly drift from
 * the design system every other RoleModel surface uses. Now Optics is upstream
 * and the video tokens are generated. Re-export from the Optics tool, drop the
 * file in, run this, and the wallpapers and presets follow.
 *
 *   node lib/sync-brand.mjs [--check]
 *
 * `--check` verifies tokens.json is current without writing — for CI.
 */
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SOURCE = resolve(ROOT, 'brand/optics-tokens.json')
const TARGET = resolve(ROOT, 'brand/tokens.json')
const CHECK = process.argv.includes('--check')

/**
 * Which Optics scales are RoleModel sub-brands, and what to call them here.
 * Everything else in the export (primary, neutral, the alerts) is app UI colour
 * and has no bearing on video.
 */
/*
 * The sub-brands this toolkit offers, which is not every scale Optics carries.
 *
 * Building, Airfield, Flow and Deck Designer were dropped: their Optics scales are
 * still in the Figma export and still correct — they are real products — but a
 * video toolkit offering eight brand choices when four of them are never used made
 * the Brand page a list to scroll rather than a decision.
 *
 * Filtered here rather than by editing brand/optics-tokens.json, because that file
 * is a Figma export: deleting from it would put them back on the next export and
 * silently disagree with Optics. This is the toolkit's own list, and it is the only
 * thing that decides what appears.
 */
const SUB_BRANDS = {
  academy: { scale: 'academy-primary', label: 'Craftsmanship Academy' },
  lcad: { scale: 'lcad', label: 'LightningCAD' },
  docks: { scale: 'docks', label: 'Dock Designer' },
  railing: { scale: 'railing', label: 'Railing Designer' },
}

/** Video-specific values Optics has no opinion about. Preserved across syncs. */
const VIDEO = {
  type: { display: 'DM Sans', body: 'DM Sans', mono: 'Geist Mono' },
  surfaces: { gridSize: 16, dotOpacity: 0.16, asciiOpacity: 0.2 },
  annotationScale: {
    $comment: 'Pixel sizes against a 1920x1080 canvas. OpenScreen annotation fontSize is in pixels on the composed frame.',
    title: 96,
    sectionHeading: 64,
    lowerThirdTitle: 44,
    lowerThirdSub: 24,
    callout: 36,
    eyebrow: 26,
  },
}

function hslToHex(h, s, l) {
  const sN = s / 100
  const lN = l / 100
  const c = (1 - Math.abs(2 * lN - 1)) * sN
  const x = c * (1 - Math.abs(((h / 60) % 2) - 1))
  const m = lN - c / 2
  const [r, g, b] = h < 60 ? [c, x, 0] : h < 120 ? [x, c, 0] : h < 180 ? [0, c, x] : h < 240 ? [0, x, c] : h < 300 ? [x, 0, c] : [c, 0, x]
  return `#${[r, g, b]
    .map((n) =>
      Math.round((n + m) * 255)
        .toString(16)
        .padStart(2, '0'),
    )
    .join('')}`
}

const num = (v) => Number.parseFloat(String(v).replace('%', ''))

/** Pull { h, s, l, hex } for every scale in the export's Primitive Colors. */
function readScales(doc) {
  const primitives = doc?.[0]?.['Primitive Colors']?.modes?.['Light Theme']
  if (!primitives) throw new Error('Unrecognised Optics export: no Primitive Colors / Light Theme.')

  const out = {}
  for (const [key, val] of Object.entries(primitives)) {
    if (!key.startsWith('op-color-') || !val?.h) continue
    const h = num(val.h.$value)
    const s = num(val.s.$value)
    const l = num(val.l.$value)
    if ([h, s, l].some(Number.isNaN)) continue
    out[key.slice('op-color-'.length)] = { h, s, l, hex: hslToHex(h, s, l) }
  }
  return out
}

function build(scales) {
  const need = (name) => {
    const s = scales[name]
    if (!s) throw new Error(`Optics export is missing the "${name}" scale.`)
    return s
  }

  const subBrands = {}
  for (const [id, { scale, label }] of Object.entries(SUB_BRANDS)) {
    const s = scales[scale]
    if (!s) {
      console.warn(`  ! no "${scale}" scale in the export — skipping sub-brand "${id}"`)
      continue
    }
    subBrands[id] = { label, opticsScale: scale, h: s.h, s: s.s, l: s.l, hex: s.hex }
  }

  return {
    $comment: 'GENERATED by lib/sync-brand.mjs from brand/optics-tokens.json. Do not hand-edit the palette or subBrands — change the Optics export and re-run.',
    $source: 'brand/optics-tokens.json',
    palette: {
      primary: need('academy-primary').hex,
      secondary: need('academy-secondary').hex,
      tertiary: need('academy-accent').hex,
      accent: need('academy-accent').hex,
      dark: need('academy-dark').hex,
      light: '#f2f2f2',
      appPrimary: need('primary').hex,
      neutral: need('neutral').hex,
    },
    rules: {
      $comment: 'From DESIGN.md: orange is an accent only, never a slide or video background.',
      orangeIsNeverABackground: true,
    },
    ...VIDEO,
    subBrands,
    unitSignatures: {
      $comment: 'Academy curriculum wayfinding — units, not sub-brands. Hand-set in DESIGN.md.',
      ruby: '#3A70B3',
      design: '#A998C9',
      rails: '#86C774',
      javascript: null,
    },
  }
}

const doc = JSON.parse(await readFile(SOURCE, 'utf8'))
const scales = readScales(doc)
const next = build(scales)
const serialized = `${JSON.stringify(next, null, 2)}\n`

if (CHECK) {
  const current = await readFile(TARGET, 'utf8').catch(() => '')
  if (current !== serialized) {
    console.error('brand/tokens.json is stale — run `node lib/sync-brand.mjs`.')
    process.exit(1)
  }
  console.log('brand/tokens.json is up to date.')
} else {
  await writeFile(TARGET, serialized, 'utf8')
  console.log(`\n  read    ${Object.keys(scales).length} Optics scales`)
  console.log(`  wrote   ${Object.keys(next.subBrands).length} sub-brands -> brand/tokens.json\n`)
  for (const [id, b] of Object.entries(next.subBrands)) {
    console.log(`    ${id.padEnd(10)} ${b.hex}  H${String(b.h).padStart(3)} S${b.s}% L${b.l}%  ${b.label}`)
  }
  console.log('')
}
