/*
 * Put the rendered wallpapers where the editor can see them.
 *
 * This lived inside make-wallpapers.mjs, which meant it only ran when someone
 * remembered to run that script. The Studio's "New wallpaper" writes its render
 * into brand/wallpapers/ and stopped there, so a wallpaper you had just made and
 * were looking at was invisible to the editor — one recipe (`rolemodel`) sat
 * stranded that way, rendered and unreachable.
 *
 * Extracted so both callers run the same code: the script, and the Studio the
 * moment it saves. Nothing here is Studio-specific; it is the install step.
 */

import { execFileSync } from "node:child_process";
import { copyFile, mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, resolve } from "node:path";

/** The picker grid loads these; the full renders are 3840x2160. */
const THUMB = 240;

/**
 * Install `recipes` (already rendered into `out`) into the OpenScreen fork.
 *
 * Returns `{ installed, fork, reason }`. A missing checkout is not an error —
 * the toolkit is usable without the fork beside it, and the caller decides
 * whether to mention it.
 */
export async function installWallpapersIntoFork({ recipes, out, fork }) {
	const pub = join(fork, "public", "wallpapers", "brand");
	if (!existsSync(join(fork, "public", "wallpapers"))) {
		return { installed: 0, fork, reason: `no OpenScreen checkout at ${fork}` };
	}

	await mkdir(join(pub, "thumbs"), { recursive: true });

	// Anything of ours without a recipe goes, so a rename does not ship both spellings.
	const want = new Set(recipes.map((r) => `${r.name}.jpg`));
	for (const dir of [pub, join(pub, "thumbs")]) {
		for (const f of await readdir(dir).catch(() => [])) {
			if (f.endsWith(".jpg") && !want.has(f)) await rm(join(dir, f));
		}
	}

	let installed = 0;
	for (const r of recipes) {
		const src = resolve(out, `${r.name}.jpg`);
		if (!existsSync(src)) continue;
		await copyFile(src, join(pub, `${r.name}.jpg`));
		/*
		 * sips rather than a second render: the swatch has to be the same picture as
		 * the wallpaper, and re-running the recipe at 240px shows texture at the
		 * wrong scale. A thumb that fails is not fatal — the picker falls back to
		 * the full image, which is slow rather than broken.
		 */
		try {
			execFileSync("sips", ["-z", String(THUMB), String(THUMB), src, "--out", join(pub, "thumbs", `${r.name}.jpg`)], {
				stdio: "ignore",
			});
		} catch {
			/* no sips (not macOS), or an image it will not read */
		}
		installed += 1;
	}

	/*
	 * Committed rather than read from disk at runtime because the fork builds in CI
	 * with no toolkit checkout beside it — the same reason optics-tokens.css is
	 * committed there. Which also means: a wallpaper added here reaches a running
	 * editor only after the fork is rebuilt.
	 */
	const manifest = [
		"// GENERATED by lib/make-wallpapers.mjs in the rolemodel-openscreen toolkit.",
		"// DO NOT EDIT. Run `npm run wallpapers` there.",
		"//",
		"// The brand wallpapers, ahead of the stock set in the picker. Committed rather",
		"// than read from disk at runtime because this fork builds in CI with no toolkit",
		"// checkout beside it — the same reason styles/optics-tokens.css is committed.",
		"",
		"export interface BrandWallpaper {",
		"\tpath: string;",
		"\tthumb: string;",
		"\tlabel: string;",
		"}",
		"",
		"export const BRAND_WALLPAPERS: readonly BrandWallpaper[] = [",
		...recipes.map(
			(r) =>
				`\t{ path: "/wallpapers/brand/${r.name}.jpg", thumb: "/wallpapers/brand/thumbs/${r.name}.jpg", label: ${JSON.stringify(r.label)} },`,
		),
		"];",
		"",
	].join("\n");
	await writeFile(join(fork, "src", "lib", "brandWallpapers.ts"), manifest, "utf8");

	return { installed, fork, reason: null };
}
